framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true
    router:
        utf8: true
    rate_limiter:
        contact:
            policy: fixed_window
            limit: '%env(int:CONTACT_RATE_LIMIT)%'
            interval: '1 minute'

when@test:
    framework:
        test: true
