monolog:
    channels: ['api']
    handlers:
        api:
            type: stream
            path: '%kernel.logs_dir%/api.log'
            level: info
            channels: ['api']
            formatter: monolog.formatter.json
        main:
            type: fingers_crossed
            action_level: warning
            handler: nested
            excluded_http_codes: [404, 405]
            channels: ['!api']
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            formatter: monolog.formatter.json
