controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_docs:
    path: /api/docs.json
    methods: [GET]
    defaults:
        _controller: nelmio_api_doc.controller.swagger

api_docs_ui:
    path: /api/docs
    methods: [GET]
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
